### ISSUE TITLE
Ability to sign in with PAT - Personal Access Token

### ISSUE THREAD

**Issue by difemaro** [glenrobinson72/Tableau-Powershell-Scripts#12]
Your library is great, thanks, thanks, thanks.  I wonder if you can modify your sign in function to use with PAT.  As you may know, Tableau Online have changed to enforce MFA.  And the old sign in would not work, and I love to have PAT authentication. 

Thanks.

Diego

**Comment by glenrobinson72** [comment]
Hi
Thanks for the positive feedback
The 3.8 psm1 module already handles PAT tokens. 
You just need to use Token  / TokenName instead of username / password
All the best
Glen
