### ISSUE TITLE
TS-UpdateProjectPermissions Bug

### ISSUE THREAD

**Issue by JBandy** [glenrobinson72/Tableau-Powershell-Scripts#2]
There is a bug preventing changes to ViewDataSource permissions on TS-UpdateProjectPermissions.

`   If ($ViewDataSource -eq 'Allow' -or $ViewDataSource -eq 'Deny'){$DataSourceCapabilities += '        <capability name="Read" mode="' + $ViewWorkbook +'" />'}`

Should be

`If ($ViewDataSource -eq 'Allow' -or $ViewDataSource -eq 'Deny'){$DataSourceCapabilities += '        <capability name="Read" mode="' + $ViewDataSource +'" />'}`

**Comment by glenrobinson72** [comment]
Thanks. Will update code
All the best
Glen
