### ISSUE TITLE
TS-GetGroupDetails Assumptions

### ISSUE THREAD

**Issue by JBandy** [glenrobinson72/Tableau-Powershell-Scripts#3]
TS-GetGroupDetails requires Domain, or defaults to local. There are other functions which use TS-GetGroupDetails in order to carry out their tasks (IE: TS-UpdateProjectPermissions) but those functions don't take a domain input, so if your not using local groups these functions don't work properly.

Quick and dirty fix to utilize TS-QueryGroups for providing the domain:

```
function TS-GetGroupDetails
{
 param(
 [string[]] $Name = "",
 [string[]] $ID = "",
 [string[]] $Domain ="local"
 )
$response = Invoke-RestMethod -Uri ${protocol}://$server/api/$api_ver/sites/$siteID/groups -Headers $headers -Method Get

 foreach ($detail in $response.tsResponse.Groups.Group)
  { 
   if ($Name -eq $detail.name -and ($Domain -eq $detail.Domain.Name -or (ts-querygroups | where {$_.Name -eq $Name}).Domain -eq $detail.Domain.Name)){Return $detail.ID}

   if ($ID -eq $detail.ID){Return $detail.Name}
  }
}
```

**Comment by glenrobinson72** [comment]
Thanks. Will take a look at this, and see what I can do to get this working properly.

**Comment by glenrobinson72** [comment]
Hi. Have updated code to handle Domain groups and permissions (and elsewhere)
Have also added Schedules Code, and Downloading revision history
