### ISSUE TITLE
Can't get the TS-UpdateWorkbookPermissions to work

### ISSUE THREAD

**Issue by makks** [glenrobinson72/Tableau-Powershell-Scripts#4]
Hi Glen! 

Thanks a lot for your work with the powershell scripts for Tableau. I am using your Backup and restore stuff and I'm now trying to get the updateWorkbookpermissions to work (I want the workbook to change permissions depending which subproject it is in) 

There seems to be something wrong with the GetgroupDetails function since it does not seem to return a GroupID that I need to run the updateworkbookpermissions. Do you know how to troubleshoot further? 

Many thanks! 
/Mats

**Comment by glenrobinson72** [comment]
Hi
Are you using AD groups or local groups? If AD are you adding the domain name too
All the best
Glen

**Comment by makks** [comment]
Hi Glen .. I have tried both .. no success .. local groups does not work either .. How do you call your TS-UpdateWorkbookPermissions can you give me an example? The function is not documented in the helpfile

Many thanks! 
/Mats

**Comment by glenrobinson72** [comment]
Hi Mats
Once logged in you should run the following (something like this

TS-UpdateWorkbookPermissions -ProjectName "My Project" -workbookName "My Workbook" -GroupName "Sales Team"-ViewWorkbook Allow -DownloadImagePDF Deny
 
If the group is a domain group then add -Domain domin.name

There are a number of Permission settings that can be updated, by setting Allow, Deny, or Blank

If the project is locked, then you wont be able to update workbook permissions separately to what has been set at the project level.

Hope this helps (and works)
Glen

**Comment by glenrobinson72** [comment]
closed
