### ISSUE TITLE
TS-Signin

### ISSUE THREAD

**Issue by vikashdaya** [glenrobinson72/Tableau-Powershell-Scripts#5]
I can't get TS-Signin to work.  The signin-body appears to be malformed. I tried replacing the quotes but still can't get this to work.  Keep getting the "Unable to Sign-In to Tableau Server" message.

**Comment by glenrobinson72** [comment]
Hi 
Try the following powershell
You will need to update the server, username, and password, and have the rights to login into the Default site
(Also, confirm which version of tableau server you are running.. the Api_ver is for 10.3 and above (i think)
Let me know what happens

$username = "YourName"
$password = "Password"
$server = "Http://servername"

$api_ver = "2.7"

 # Login to Server
 # generate body for sign in
 $signin_body = (’<tsRequest>
  <credentials name=“’ + $username + ’” password=“’+ $password + ’” >
   <site contentUrl="’’"/>
  </credentials>
 </tsRequest>’)

 $Uri = "$server/api/$api_ver/auth/signin"
 $response = Invoke-RestMethod -Uri $uri -Body $signin_body -Method Post  

 # get the auth token, site id and my user id
 $authToken = $response.tsResponse.credentials.token
 $headers = New-Object “System.Collections.Generic.Dictionary[[String],[String]]”
 $headers.Add(“X-Tableau-Auth”, $authToken)
 $authToken

**Comment by vikashdaya** [comment]
I've updated the signin_body code to the following to make it work... 

$signin_body = (```'<tsRequest><credentials name="' + $username + '" password="'+ $password + '"><site contentUrl="' + $siteID + '"/></credentials></tsRequest>'```)

Also, had to change the quotes for **$headers.Add("X-Tableau-Auth", $authToken)**

**Comment by glenrobinson72** [comment]
Thanks.. It looks like when i copied the code into the message, it dropped some of it (esp around the signin body.
Glad that its working for you though
Glen
