### ISSUE TITLE
Enhancement for multi-part upload

### ISSUE THREAD

**Issue by gbutler201** [glenrobinson72/Tableau-Powershell-Scripts#6]
Hi Glen, I've found your module library exceedingly helpful in developing a suite of tools around Tableau Server for my IT team colleagues.
I want to return the (blind) favour by supplying you a copy of my modified code as I've actually made quite a few changes including two new functions which implement chunked file upload for workbooks and data sources. So if you are interested in rolling the essence of these changes into your library baseline, I'm more than happy for you to do this :) 
Also note I've added a C# block to improve System.Net.Webclient handling, and in my new functions have added some sanitizing around XML payloads.
[Tableau-REST.psm1.txt](https://github.com/glenrobinson72/Tableau-Powershell-Scripts/files/2104776/Tableau-REST.psm1.txt)
Best regards, Gavin.

**Comment by glenrobinson72** [comment]
Thanks Gavin. 
Will take a look at what you've done. I have some updates for ver 3.0 (2018.1) which I haven't yet published. (Things like filtering, etc)
I am thinking about just starting again with a new version, and not update the current version, so will look at your updates, and add them too..
Out of interest, what sort of things are you doing with the REST API? How extensively do you use it? Are there any issues, etc?
All the best
Glen

**Comment by gbutler201** [comment]
Hi Glen,

We’re using your library for automation of content migration from one Tableau site to another, and this has proven very effective and a huge time saver. Existing tools like tabcmd and TabMigrate need repetitive use to achieve the desired result and/or require manual follow-on steps, or if commercially available come with a large associated price tag. I would’ve liked to implement async workbook publishing as well but we are on 10.4 (2.7) now; we’re looking to upgrade fairly soon though (2-3 months).

We also populate some local user groups from Active Directory groups using your functions: this sounds counter-intuitive but there exists a limitation where Tableau only recognizes local groups via the ISMEMBEROF() function – see [https://community.tableau.com/ideas/8525](https://community.tableau.com/ideas/8525)  (please vote/share if of interest!)

Elsewhere, we use the API (not via Powershell but C#) to service a Web Portal front end, which supports usage of the Javascript API. This is running 24x7 and reads user-workbook viewership via the REST API. So yes we use the REST API quite a bit I think, although we are pretty new to Tableau (last 12 months) I suspect our API use cases are fairly business specific.

The only two issues I had with your original code were:
- if an XML payload contains a filename with an un-escaped ampersand or other special character this would result in a 400 error. Sanitizing the filename with HTML encoding fixes this.
- your functions catch errors and print a message but don’t re-throw an error to be caught higher up. You may spot that I made this adjustment broadly in the script I supplied, it was just more useful to me to have errors propagated.

Thanks again for your great work, I wouldn’t have been able to deliver such useful outcomes for our business without it! Plus I learnt a shed-load about Powershell in the process :) I look forward to seeing your updates when you get around to publishing them.

Cheers,
Gavin.

**Comment by glenrobinson72** [comment]
closed

**Comment by glenrobinson72** [comment]
Hi Gavin, 
Just to let you know, I have (finally) published a new version of the REST API Wrapper to github, for Tableau Server 2018.3
This version includes your additions to my script, among a load of other additions, so thanks for that. It works really well..
All the best
Glen
