### ISSUE TITLE
`Invoke-RestMethod : 'utf8' is not a supported encoding name.

### ISSUE THREAD

**Issue by icevoodoo** [glenrobinson72/Tableau-Powershell-Scripts#8]
Hi Glen,

When i run a script in powershel on the statement bellow I get an error.
Please advice. I'm not a super programmer in powershell. Maybe I do something wrong...
I need to get the tableau userid and the single method that I can use is the one bellow.

`$response = Invoke-RestMethod -Uri $server/api/$api_ver/sites/$siteID/users?filter=name:eq:$username -Headers $headers -Method Get`

`Invoke-RestMethod : 'utf8' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
At C:\Users\msso.admin\Documents\WindowsPowerShell\Scripts\change_users_password.ps1:33 char:14
+     $response = Invoke-RestMethod -Uri $server/api/$api_ver/sites/$siteID/users?fil ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by glenrobinson72** [comment]
Hi,
I cant really tell from the information you have sent me.. 
Are you able to upload the actual script itself, and I will take a look at that
All the best
Glen

**Comment by glenrobinson72** [comment]
No further response
