### ISSUE TITLE
Tableau REST API Helpfile

### ISSUE THREAD

**Issue by yapnel** [glenrobinson72/Tableau-Powershell-Scripts#9]
Hi Glen,

Many thanks for your PowerShell scripts for Tableau REST API. 

By any chance, you will also be updating the helpfile to reflect on the newer 3.2 API script?

THanks

Nelson

**Comment by glenrobinson72** [comment]
Hi Nelson 
Thanks for the feed back. 
I am working on the new features on 2019.1 (ie managing flows) first, but will also spend some time on getting the help file up to date too.
Have no time lines just yet though
Thanks
Glen
